.PHONY : all

hello := hello world.

override fine = I'm fine.

define happy
I'm happy.
endef

define cmd
	@echo "run cmd"
	@dir
endef

all :
	@echo "$(hello)"
	@echo "$(fine)"
	@echo "$(happy)"
	$(cmd)