all : first second third
	@echo "$$@ = $@"
	@echo "$$^ = $^"
	@echo "$$< = $<"

first :
	@echo "$$@ = $@"
	@echo "$$^ = $^"
	@echo "$$< = $<"

second :
	@echo "$$@ = $@"
	@echo "$$^ = $^"
	@echo "$$< = $<"

third :
	@echo "$$@ = $@"
	@echo "$$^ = $^"
	@echo "$$< = $<"